from class_smartphone import *
smartphones = Smartphone()
smartphones.agregar_al_final('Iphone')
smartphones.agregar_al_final('Samsung')
smartphones.agregar_al_final('LG')
smartphones.agregar_al_final('Huawei')
smartphones.agregar_al_final('Motorola')
smartphones.transversal()
smartphones.eliminar_posicion(2)
smartphones.transversal()
smartphones.actualizar('Motorola', 'Xiaomi')
smartphones.agregar_al_inicio('Nexus')
smartphones.agregar_al_final('Oppo')
smartphones.transversal()
smartphones.eliminar_primero()
smartphones.transversal()
