from tarea_5 import *
print('*** Lista doblemente ligada ***')
numeros = DoubleLinkedList()
numeros.agregar_al_inicio(50)
numeros.agregar_al_final(60)
numeros.agregar_al_final(65)
numeros.agregar_al_final(70)
numeros.agregar_al_final(80)
numeros.agregar_al_final(90)
numeros.transversal()
numeros.eliminar_posicion(2)
numeros.transversal()
numeros.actualizar(4, 88)
numeros.transversal()
numeros.buscar_valor(88)
